# Generated by Django 3.0.4 on 2020-04-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('canned_response', models.TextField(blank=True, null=True)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='triage.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='case_request', serialize=False, to='chat.Message')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.News')),
                ('response', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_response', to='chat.Message')),
            ],
        ),
    ]
