# Generated by Django 3.0.4 on 2020-04-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('is_incoming', models.BooleanField()),
                ('body', models.TextField()),
                ('dt', models.DateTimeField(null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=34, null=True)),
                ('twilio_message_sid', models.CharField(blank=True, max_length=34, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64, null=True)),
                ('twilio_media_url', models.CharField(max_length=1024)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Message')),
            ],
        ),
    ]
